
FROM python:3.9-alpine

RUN apk add --no-cache \
    bash \
    build-base \
    meson \
    nasm \
    yasm \
    git \
    python3-dev \
    libgcc \
    libtool \
    libpng-dev \
    jpeg-dev \
    zlib-dev \
    linux-headers \ 
    vim  \
    nano \
    x264-dev \
    x265-dev \
    libvpx-dev \
    libvorbis-dev \
    opus-dev \
    aom-dev

RUN pip3 install matplotlib pandas

RUN git clone https://github.com/Netflix/vmaf.git /vmaf \
    && cd /vmaf/libvmaf \
    && meson build --buildtype release \
    && ninja -C build \
    && ninja -C build install

RUN git clone https://git.ffmpeg.org/ffmpeg.git /ffmpeg \
    && cd /ffmpeg \
    && ./configure --enable-gpl  --enable-libvmaf --enable-libx264 --enable-libx265 --enable-libaom --enable-libvpx --enable-libvorbis --enable-libopus \
    && make -j4 \
    && make install


RUN mkdir -p /inputs /results

WORKDIR /app

COPY analyze.py .
COPY run_experiments.sh .

RUN chmod +x run_experiments.sh analyze.py

RUN ./run_experiments.sh

CMD ["/bin/sh"]
